"""Shared constants for plotting utilities."""

# Time boundaries
DAYS_IN_WEEK = 7
DAY_INDEX_MIN = 0
DAY_INDEX_MAX = 6

MONTHS_IN_YEAR = 12
MONTH_INDEX_MIN = 1
MONTH_INDEX_MAX = 12

HOURS_IN_DAY = 24
HOUR_INDEX_MIN = 0
HOUR_INDEX_MAX = 23

# Figure dimensions
FIGURE_WIDTH_LARGE = 12
FIGURE_WIDTH_STANDARD = 10
FIGURE_HEIGHT = 6
FIGURE_SIZE_SQUARE = 6

# Output settings
SAVE_DPI_HIGH = 300
SAVE_DPI_STANDARD = 150
PIE_START_ANGLE = 90
GRID_ALPHA = 0.7
XLABEL_ROTATION = 45

# WordCloud settings
WORDCLOUD_WIDTH = 1200
WORDCLOUD_HEIGHT = 600
WORDCLOUD_MAX_FONT_SIZE = 120
WORDCLOUD_PREFER_HORIZONTAL = 0.7
